# Generated by Django 5.2.7 on 2025-11-18 18:43

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('BAJO_STOCK', 'Bajo Stock'), ('SOBRE_STOCK', 'Sobre Stock'), ('POR_VENCER', 'Por Vencer'), ('VENCIDO', 'Vencido'), ('SIN_STOCK', 'Sin Stock')], max_length=20)),
                ('cantidad_actual', models.DecimalField(decimal_places=6, max_digits=18)),
                ('cantidad_limite', models.DecimalField(blank=True, decimal_places=6, help_text='Stock mínimo/máximo según tipo de alerta', max_digits=18, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Obligatorio para POR_VENCER, VENCIDO', null=True)),
                ('dias_vencimiento', models.IntegerField(blank=True, help_text='Días hasta vencimiento para POR_VENCER', null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada')], default='ACTIVA', max_length=20)),
                ('fecha_generacion', models.DateTimeField()),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('motivo_resolucion', models.TextField(blank=True, help_text='Explicación de cómo se resolvió', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'db_table': 'alertas_stock',
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SUCURSAL', 'Sucursal'), ('TRANSITO', 'Tránsito')], default='PRINCIPAL', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodegas',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('fecha_produccion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Obligatorio si producto.perishable = true', null=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=6, max_digits=18)),
                ('cantidad_disponible', models.DecimalField(decimal_places=6, help_text='Debe ser <= cantidad_inicial', max_digits=18)),
                ('cantidad_reservada', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=6, help_text='Costo unitario del lote', max_digits=18, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('AGOTADO', 'Agotado'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=20)),
                ('motivo_bloqueo', models.TextField(blank=True, help_text='Razón del bloqueo si estado = BLOQUEADO', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('fecha_movimiento', models.DateTimeField()),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=18)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('serie', models.CharField(blank=True, help_text='Obligatorio si producto.control_por_serie = true', max_length=100, null=True)),
                ('documento_padre_tipo', models.CharField(blank=True, choices=[('ORDEN_COMPRA', 'Orden de Compra'), ('ORDEN_VENTA', 'Orden de Venta'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('TRANSFERENCIA_INTERNA', 'Transferencia Interna'), ('DEVOLUCION_CLIENTE', 'Devolución Cliente'), ('DEVOLUCION_PROVEEDOR', 'Devolución Proveedor')], max_length=30, null=True)),
                ('documento_padre_id', models.IntegerField(blank=True, help_text='ID del documento que origina el movimiento', null=True)),
                ('documento_referencia', models.CharField(blank=True, help_text='Factura, guía despacho, etc', max_length=50, null=True)),
                ('motivo_ajuste', models.TextField(blank=True, help_text='Obligatorio para AJUSTE y DEVOLUCION', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, help_text='Fecha de confirmación del movimiento', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientos_inventario',
            },
        ),
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('cantidad_reservada', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('cantidad_transito', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('ultima_salida', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Actual',
                'verbose_name_plural': 'Stock Actual',
                'db_table': 'stock_actual',
            },
        ),
    ]
