# Generated by Django 5.2.7 on 2025-11-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('inventario', '0001_initial'),
        ('maestros', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertastock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='resuelto_por_usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que marcó como resuelta', null=True, on_delete=django.db.models.deletion.PROTECT, to='autenticacion.usuario'),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='bodega',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para BAJO_STOCK, SOBRE_STOCK, SIN_STOCK', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='lote',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor del lote', null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.proveedor'),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para POR_VENCER, VENCIDO', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para INGRESO y TRANSFERENCIA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega_origen',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para SALIDA, AJUSTE y TRANSFERENCIA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Obligatorio si producto.control_por_lote = true', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para INGRESO y DEVOLUCION', null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.proveedor'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.unidadmedida'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacion.usuario'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario_confirmacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que confirmó el movimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_confirmados', to='autenticacion.usuario'),
        ),
        migrations.AddField(
            model_name='stockactual',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='stockactual',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['codigo_lote'], name='lotes_codigo__211d52_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['producto'], name='lotes_product_fd9590_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['fecha_vencimiento'], name='lotes_fecha_v_ce4cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['estado'], name='lotes_estado_a6768b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['producto'], name='alertas_sto_product_d45301_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['tipo_alerta'], name='alertas_sto_tipo_al_b5f8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['estado'], name='alertas_sto_estado_ff48e6_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['fecha_generacion'], name='alertas_sto_fecha_g_257108_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento'], name='movimientos_tipo_mo_a03876_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha_movimiento'], name='movimientos_fecha_m_c279a0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto'], name='movimientos_product_3deae0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['estado'], name='movimientos_estado_e517b7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockactual',
            index=models.Index(fields=['producto'], name='stock_actua_product_ceb510_idx'),
        ),
        migrations.AddIndex(
            model_name='stockactual',
            index=models.Index(fields=['bodega'], name='stock_actua_bodega__c267d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockactual',
            unique_together={('producto', 'bodega')},
        ),
    ]
