# Generated by Django 5.2.7 on 2025-11-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='usuarios/fotos/'),
        ),
    ]
