# Generated by Django 5.2.7 on 2025-11-18 18:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=6, help_text='Costo del producto con este proveedor', max_digits=18)),
                ('lead_time_dias', models.IntegerField(default=7, help_text='Tiempo de entrega en días')),
                ('min_lote', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Cantidad mínima de compra', max_digits=18)),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento', max_digits=5, null=True)),
                ('preferente', models.BooleanField(default=False, help_text='Proveedor preferente')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto-Proveedor',
                'verbose_name_plural': 'Productos-Proveedores',
                'db_table': 'productos_proveedores',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nif', models.CharField(help_text='RUT o NIF único', max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=128, null=True)),
                ('pais', models.CharField(default='Chile', max_length=64)),
                ('condiciones_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('30_DIAS', '30 días'), ('60_DIAS', '60 días'), ('90_DIAS', '90 días'), ('OTRO', 'Otro')], max_length=20)),
                ('condiciones_pago_detalle', models.CharField(blank=True, help_text='Detalle si es OTRO', max_length=255, null=True)),
                ('moneda', models.CharField(default='CLP', help_text='Código ISO moneda', max_length=8)),
                ('contacto_principal_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('contacto_principal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_principal_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la unidad (ej: KG, L, UND)', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo de la unidad', max_length=50)),
                ('tipo', models.CharField(choices=[('PESO', 'Peso'), ('VOLUMEN', 'Volumen'), ('LONGITUD', 'Longitud'), ('UNIDAD', 'Unidad'), ('TIEMPO', 'Tiempo')], max_length=20)),
                ('factor_base', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Factor de conversión a unidad base del tipo', max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidades_medida',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria_padre', models.ForeignKey(blank=True, help_text='Para subcategorías', null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
    ]
