# Generated by Django 5.2.7 on 2025-11-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoproveedor',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['rut_nif'], name='proveedores_rut_nif_5ef129_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['estado'], name='proveedores_estado_e45323_idx'),
        ),
        migrations.AddField(
            model_name='productoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.proveedor'),
        ),
        migrations.AddIndex(
            model_name='unidadmedida',
            index=models.Index(fields=['codigo'], name='unidades_me_codigo_8dd584_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadmedida',
            index=models.Index(fields=['tipo'], name='unidades_me_tipo_6f70c3_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadmedida',
            index=models.Index(fields=['activo'], name='unidades_me_activo_995d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='productoproveedor',
            index=models.Index(fields=['producto'], name='productos_p_product_06bc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='productoproveedor',
            index=models.Index(fields=['proveedor'], name='productos_p_proveed_581a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='productoproveedor',
            index=models.Index(fields=['preferente'], name='productos_p_prefere_eb83fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productoproveedor',
            unique_together={('producto', 'proveedor')},
        ),
    ]
