# Generated by Django 5.2.7 on 2025-11-18 18:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código SKU único', max_length=50, unique=True)),
                ('ean_upc', models.CharField(blank=True, help_text='Código de barras EAN/UPC (opcional, único si se usa)', max_length=20, null=True)),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada', null=True)),
                ('modelo', models.CharField(blank=True, help_text='Modelo del producto (opcional)', max_length=100, null=True)),
                ('factor_conversion', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Factor conversión de compra a venta (default 1)', max_digits=10)),
                ('costo_estandar', models.DecimalField(blank=True, decimal_places=2, help_text='Costo estándar del producto (opcional)', max_digits=18, null=True)),
                ('costo_promedio', models.DecimalField(blank=True, decimal_places=2, help_text='Costo promedio (solo lectura, calculado automáticamente)', max_digits=18, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta (opcional)', max_digits=18, null=True)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=Decimal('19'), help_text='Porcentaje IVA (ej: 19 para 19%)', max_digits=5)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Stock actual (calculado automáticamente)', max_digits=18)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Stock mínimo (default 0)', max_digits=18)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Stock máximo (opcional)', max_digits=18, null=True)),
                ('punto_reorden', models.DecimalField(blank=True, decimal_places=2, help_text='Punto de reorden (opcional, si no se usa el mínimo)', max_digits=18, null=True)),
                ('perecible', models.BooleanField(default=False, help_text='Producto perecedero')),
                ('control_por_lote', models.BooleanField(default=False, help_text='Requiere control por lote')),
                ('control_por_serie', models.BooleanField(default=False, help_text='Requiere control por número de serie')),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen del producto (opcional)', max_length=500, null=True)),
                ('ficha_tecnica_url', models.URLField(blank=True, help_text='URL de la ficha técnica PDF (opcional)', max_length=500, null=True)),
                ('alerta_bajo_stock', models.BooleanField(default=False, editable=False, help_text='Se activa cuando stock_actual < stock_minimo')),
                ('alerta_por_vencer', models.BooleanField(default=False, editable=False, help_text='Se activa cuando hay lotes próximos a vencer')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('DESCONTINUADO', 'Descontinuado')], default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría del producto', on_delete=django.db.models.deletion.PROTECT, to='maestros.categoria')),
                ('marca', models.ForeignKey(blank=True, help_text='Marca del producto (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.marca')),
                ('uom_compra', models.ForeignKey(help_text='Unidad de medida para compra', on_delete=django.db.models.deletion.PROTECT, related_name='productos_compra', to='maestros.unidadmedida')),
                ('uom_venta', models.ForeignKey(help_text='Unidad de medida para venta', on_delete=django.db.models.deletion.PROTECT, related_name='productos_venta', to='maestros.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku'], name='productos_sku_a62667_idx'), models.Index(fields=['categoria'], name='productos_categor_169a62_idx'), models.Index(fields=['estado'], name='productos_estado_184900_idx'), models.Index(fields=['alerta_bajo_stock'], name='productos_alerta__b78389_idx')],
            },
        ),
    ]
