# Generated by Django 5.2.7 on 2025-11-18 18:43

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('fecha_orden', models.DateField()),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada'), ('RECIBIDA_PARCIAL', 'Recibida Parcial'), ('RECIBIDA_COMPLETA', 'Recibida Completa'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('moneda', models.CharField(default='CLP', max_length=8)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'db_table': 'ordenes_compra',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=6, max_digits=18)),
                ('cantidad_recibida', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle Orden de Compra',
                'verbose_name_plural': 'Detalles Órdenes de Compra',
                'db_table': 'ordenes_compra_detalle',
            },
        ),
    ]
