# Generated by Django 5.2.7 on 2025-11-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('compras', '0001_initial'),
        ('maestros', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario_autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_autorizadas', to='autenticacion.usuario'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to='autenticacion.usuario'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.unidadmedida'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['numero_orden'], name='ordenes_com_numero__72b9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor'], name='ordenes_com_proveed_6d9c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estado'], name='ordenes_com_estado_8ac831_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['fecha_orden'], name='ordenes_com_fecha_o_6951ee_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompradetalle',
            index=models.Index(fields=['orden_compra'], name='ordenes_com_orden_c_33f8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompradetalle',
            index=models.Index(fields=['producto'], name='ordenes_com_product_2cc5b4_idx'),
        ),
    ]
